### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by Antiarchitect** [opsdis/icinga2-exporter#35]
Here is my Dockerfile:

```
FROM python:3.10.6-bullseye
WORKDIR /app/icinga2-exporter
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl openssl \
    && curl -sqL "https://github.com/opsdis/icinga2-exporter/archive/refs/tags/v1.3.0.tar.gz" | tar --strip-components=1 -xzf - -C . \
    && pip install -r requirements.txt \
    && python setup.py sdist \
    && pip install dist/icinga2-exporter-0.0.1.tar.gz \
    && rm -rf dist \
    && pip install gunicorn uvicorn pyOpenSSL

CMD gunicorn --access-logfile /dev/stdout -w 4 -k uvicorn.workers.UvicornWorker "wsgi:create_app('/app/icinga2-exporter/config.yml')"
```

Here is the config.yml:

```
    icinga2:
      url: https://127.0.0.1:5665
      user: icingaweb2
      passwd: xxx
      metric_prefix: icinga2
      verify: false
```

This is what I'm getting after `curl 127.0.0.1:8000/metrics`:

```
{"timestamp": "2022-08-12T11:19:41.659402Z", "level": "WARNING", "name": "icinga2-exporter", "message": "Connection error", "target": null, "url": "http://127.0.0.1:8000/metrics", "remote_url": "https://127.0.0.1:5665", "err": "Cannot connect to host 127.0.0.1:5665 ssl:False [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]"}
```
